knpu_oauth2_client:
    clients:
        keycloak:
            provider_class: Stevenmaguire\OAuth2\Client\Provider\Keycloak
            type: generic
            client_id: '%env(KEYCLOAK_CLIENT_ID)%'
            client_secret: '%env(KEYCLOAK_CLIENT_SECRET)%'
            use_state: true # Recommended for security
            redirect_route: connect_keycloak_check
            provider_options:
                authServerUrl: '%env(KEYCLOAK_AUTH_SERVER_URL)%'
                realm: '%env(KEYCLOAK_REALM)%'
                openid: true
                scope: 'openid profile email'